### ISSUE TITLE
Custom CSS not loading

### ISSUE THREAD

**Issue by rotarydialer** [zzossig/hugo-theme-zdoc#2]
I am following the steps [here](https://zzodocs.netlify.com/docs/customization/customcss/) to add my own custom CSS.

I've added the following line to `config/_default/params.toml`:

```
custom_css = ["css/mystyles.css"]
```

I've created the file `assets/css/mystyles.css` and added these to it:

```
.navbar__logo--text {
    font-family: Verdana, sans-serif;
    color: #f00;
}

#body {
    background-color: red !important;
}
```

No changes appear. The dev tools show that the only stylesheet being loaded is `main.min.css`.

**Comment by zzossig** [comment]
I committed code just now.
Can you update the theme and check again?

**Comment by rotarydialer** [comment]
I updated (I'm at commit `6d70dd6250781e5d96dd473969a57f6863b61049` / "landing page in progress") but it's still not picking up my custom css.

**Comment by rotarydialer** [comment]
Let me know if I can provide any details that would be helpful in troubleshooting. Thanks for responding so swiftly!

**Comment by rotarydialer** [comment]
Disregard. It is picking up the file now, though the example in the docs of changing the background color isn't working.

Thank you for the fix!

**Comment by edhilgendorf** [comment]
Hi @rotarydialer , I am trying to do the same, except change font-size site wide. In the Hugo project root directory i also created  `css/mystyles.css`
with contents:
`.single__contents h2 {
font-size: 1.5rem;
}`
to change the size of all  H2 text, but I am not seeing this reflected. Did these steps work for you, and how can you confirm? Thank you

**Comment by zzossig** [comment]
@edhilgendorf 
The point is, the styles are sometimes not hot-reloaded with Hugo. You should stop and restart the Hugo.
After some restarts, it is hot-reloaded. I don't know why.

To apply custom CSS,
1. Make `assets` folder to your root directory
2. Make a CSS file with your preferred directory path
3. Add config param to `config.toml` file something like this.
```toml
custom_css = ["css/mystyles.css"]
```
4. If styles not applied, restart Hugo.
5. If styles not applied, set `!important` keyword something like this
```css
.single__contents h2 { font-size: 5.5rem !important;  }
```
